export {default as Home} from './homeRoute'
export {default as Login} from './loginRoute'
export {default as Sidebar} from './sideBar'
export {default as Userprofile} from './userProfile'
export {default as Pins} from './pins'
